services:
  database:
    container_name: slouka-database
    image: postgres:17-bookworm
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - slouka-net
    volumes:
      - ./var/postgresql:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    container_name: slouka-redis
    image: redis:bookworm
    networks:
      - slouka-net
    volumes:
      - ./var/redis:/data

  bot:
    container_name: slouka-bot
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - slouka-net

  worker:
    container_name: slouka-worker
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - slouka-net

  scheduler:
    container_name: slouka-scheduler
    depends_on:
      redis:
        condition: service_started
    networks:
      - slouka-net

networks:
  slouka-net:
    driver: bridge
