services:
  database:
    ports:
      - "5432:5432"

  redis:
    ports:
      - "6379:6379"

  bot:
    build:
      context: ./bot
      dockerfile: Dockerfile.dev
    volumes:
      - ./bot/src:/bot/src
      - ./bot/migrations:/bot/migrations

  worker:
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./bot/src:/bot/src
    env_file: ./bot/.env
    command: ["taskiq", "worker", "src.worker.tasks:broker"]

  scheduler:
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./bot/src:/bot/src
    env_file: ./bot/.env
    command: ["taskiq", "scheduler", "src.worker.broker:scheduler", "src.worker.tasks"]

networks:
  slouka-net:
    driver: bridge
