FROM ghcr.io/astral-sh/uv:python3.14-bookworm-slim

WORKDIR /bot

ENV UV_COMPILE_BYTECODE=1
ENV UV_LINK_MODE=copy
ENV UV_PYTHON_DOWNLOADS=never

RUN --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project --group dev

COPY . /bot
RUN uv sync --locked --group dev

ENV PATH="/bot/.venv/bin:$PATH"

ENTRYPOINT []

CMD ["sh", "-c", "alembic upgrade head && watchfiles 'python -m src.main' /bot/src"]
