"""add notification fields to user

Revision ID: adf117830d08
Revises: a8e8f3bfffab
Create Date: 2026-03-31 10:55:46.825772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adf117830d08'
down_revision: Union[str, Sequence[str], None] = 'a8e8f3bfffab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notifications_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('notification_hour', sa.Integer(), server_default='9', nullable=False))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), server_default='Europe/Minsk', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'notification_hour')
    op.drop_column('users', 'notifications_enabled')
    # ### end Alembic commands ###
