"""add_notification_minute_to_user

Revision ID: 38e5915bd562
Revises: cfa3925ebc43
Create Date: 2026-04-06 07:52:42.095427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38e5915bd562'
down_revision: Union[str, Sequence[str], None] = 'cfa3925ebc43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('notification_minute', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notification_minute')
    # ### end Alembic commands ###
