"""add unique constraint deck_id word on cards

Revision ID: 5c288c32eb10
Revises: 6bc0ab69f1a0
Create Date: 2026-04-06 19:13:44.570353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c288c32eb10'
down_revision: Union[str, Sequence[str], None] = '6bc0ab69f1a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cards_deck_id_word', 'cards', ['deck_id', 'word'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_cards_deck_id_word', 'cards', type_='unique')
    # ### end Alembic commands ###
