"""add indexes for cards and decks

Revision ID: 6bc0ab69f1a0
Revises: 38e5915bd562
Create Date: 2026-04-06 13:09:39.896147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bc0ab69f1a0'
down_revision: Union[str, Sequence[str], None] = '38e5915bd562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_cards_deck_id_next_review_date', 'cards', ['deck_id', 'next_review_date'], unique=False)
    op.create_index('ix_cards_is_new', 'cards', ['is_new'], unique=False, postgresql_where=sa.text('is_new = true'))
    op.create_index('ix_decks_user_id', 'decks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_decks_user_id', table_name='decks')
    op.drop_index('ix_cards_is_new', table_name='cards', postgresql_where=sa.text('is_new = true'))
    op.drop_index('ix_cards_deck_id_next_review_date', table_name='cards')
    # ### end Alembic commands ###
