"""add cascade delete on cards FK

Revision ID: 659ee8cc58c3
Revises: adf117830d08
Create Date: 2026-03-31 17:59:25.089001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '659ee8cc58c3'
down_revision: Union[str, Sequence[str], None] = 'adf117830d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cards_deck_id_fkey'), 'cards', type_='foreignkey')
    op.create_foreign_key(op.f('cards_deck_id_fkey'), 'cards', 'decks', ['deck_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cards_deck_id_fkey'), 'cards', type_='foreignkey')
    op.create_foreign_key(op.f('cards_deck_id_fkey'), 'cards', 'decks', ['deck_id'], ['id'])
    # ### end Alembic commands ###
