"""rename review_logs to activity_logs and add activity_type

Revision ID: 5865ee548326
Revises: 4cc2f7cbb1e8
Create Date: 2026-04-09 11:27:00.886140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5865ee548326'
down_revision: Union[str, Sequence[str], None] = '4cc2f7cbb1e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=20), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_logs_user_created', 'activity_logs', ['user_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_review_logs_user_reviewed'), table_name='review_logs')
    op.drop_table('review_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_logs',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('card_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quality', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('review_logs_card_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('review_logs_pkey'))
    )
    op.create_index(op.f('ix_review_logs_user_reviewed'), 'review_logs', ['user_id', 'reviewed_at'], unique=False)
    op.drop_index('ix_activity_logs_user_created', table_name='activity_logs')
    op.drop_table('activity_logs')
    # ### end Alembic commands ###
