"""add streak fields to user

Revision ID: 2d0ec774973b
Revises: 5c288c32eb10
Create Date: 2026-04-08 13:11:27.425501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0ec774973b'
down_revision: Union[str, Sequence[str], None] = '5c288c32eb10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('longest_streak', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('last_activity_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_activity_date')
    op.drop_column('users', 'longest_streak')
    op.drop_column('users', 'current_streak')
    # ### end Alembic commands ###
