"""add review_logs table

Revision ID: 4cc2f7cbb1e8
Revises: 2d0ec774973b
Create Date: 2026-04-08 17:28:58.373152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cc2f7cbb1e8'
down_revision: Union[str, Sequence[str], None] = '2d0ec774973b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_review_logs_user_reviewed', 'review_logs', ['user_id', 'reviewed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_review_logs_user_reviewed', table_name='review_logs')
    op.drop_table('review_logs')
    # ### end Alembic commands ###
